version: '3.8'

services:
  web:
    build: .
    container_name: translator_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: translationservice
    restart: always
    environment:
      POSTGRES_USER: tammy
      POSTGRES_PASSWORD: tamm
      POSTGRES_DB: translationservice
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
